language: php
dist: bionic
group: edge
os: linux
env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
branches:
  only:
  - develop
  - 3.6
services:
- mysql
- postgresql
jobs:
  fast_finish: true
  include:
  - php: 7.4
    env: DB=mysql
  - php: 7.4
    env: DB=pgsql
  - php: 7.3
    env: DB=mysql
  - php: 7.3
    env: DB=pgsql
  - php: 7.2
    env: DB=mysql
  - php: 7.2
    env: DB=pgsql
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.npm"
addons:
  postgresql: "9.6"
install:
- |
  if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
    # disable xdebug for performance reasons when code coverage is not needed.
    phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  fi

  # install composer dependencies
  export PATH="$HOME/.composer/vendor/bin:$PATH"
  composer validate
  travis_retry composer install $DEFAULT_COMPOSER_FLAGS
before_script:
- |
  # show some version and environment information
  php --version
  composer --version
  php -r "echo INTL_ICU_VERSION . \"\n\";"
  php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  psql --version
  mysql --version
  sudo mysql_upgrade || echo "MySQL is already up to date"
- travis_retry mysql -e 'CREATE DATABASE `craft-test`;';
- mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
- psql -U postgres -c 'CREATE DATABASE "craft-test";';
- pear config-set preferred_state beta
- pecl channel-update pecl.php.net
- yes | pecl install imagick
- cp tests/.env.example.$DB tests/.env
- |
  if [[ $DB == "mysql" ]]; then
    sed -i 's/DB_USER="craft"/DB_USER="root"/' tests/.env
  else
    sed -i 's/DB_USER="craft"/DB_USER="postgres"/' tests/.env
  fi
script:
- |
  if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
    vendor/bin/codecept run unit,functional
  else
    mkdir -p build/logs
    vendor/bin/codecept run unit,functional --coverage-xml coverage.xml;
  fi
after_script:
- |
  if [ $TASK_TESTS_COVERAGE == 1 ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
notifications:
  webhooks:
    urls:
      - secure: "KJkxhMBQfPffxwQwNwFsrKAlaHkFkzNgWt49qNA4K7TcTj3PSQ0yNhYt0QDFLqqphltn8YGmtXe//zJLLdKxnhXyZcQ0o6JigZeULv4DF/2uoezgTyfb+xI9VU8n3z8B9TrNow77EvLuzROY5SL4puymNhEFq3bAKwXByR9nLd0ADEv2jKwEh++Pp6EjIyIV+KYKXKSfsBIiL12QLwZyT6ysAEzab8ZcZDpvws5FpSfm3D+TmhHuSW2g4+waPbqBTYB86/bz4DEsKf4S6sPL0Fe3ekPU6V4ou6r4DE/GJLajGJAz6gKJBuZxhh3bP2GqHOyFWW+bIXPzQ70/pQmjq6UgFqaHrDbcRqOYbYiuNluSgGyf3n0Aa4CqwsUoYH7tq7yKaNgTrguAU9PGIZYZnBKRDDxg0yAjDsujejgLQFF7gYKg6HT5TgVLU2Qt72w+M9Uq+rA9D4b0UMKObR/1wjRw/FQhCJ03QvXAHdb5NaxIbZIAr3mi831zXyZsp273GaCN6IPvNzTuA2aKi2YBj5MS+72Ev3KcfxBi+ig2MwzwJ2sWp14ayUs/m6opTlUmPSqyDk38d+xM3KcR4u7td/lemaxKgfkF0z6r0GGKdqnu2gp2+GnZDqUkHtgP5jWJP5A9ssu56H06CpyS+8d95VMUtVp/QyWhe16oDjCj6nk="
      - secure: "mxx/EEbb44t/GqM755sGxTLpPrxPqiH69ptqyHvYYRk/FJeSG7AT6uOF1483QO8+beaif10HFEzKeE1OM4aOKPjz7pahAuLAp8DzzX9NxMS07zViu0nYPNYgq1URUrwJ3WQIgdkWboefVOweJf4rhDNqdkausdIFofUag6xZfPe2fz1qBdDBbkhBt+MpOTx1azp9Bc24mScJoy0076cKs7O/CItQI9572Ir9ek460QZ7hQXdR3W7POavO3TZjeOaew1Opa8Aq2Q6c90g2cXpqOVsWbk0meVow1REY+ik82eykPCTGwa02DoheB8C+nAFfqE7Vy0bladXRrt2204mSckfGjtA/gYlY9g7LcxdrU1qdXkLM0JgZr3x3U8Ds7FlqiIW5+xM1500GU5NflmxzBhyb3pBPovFEqv8xnkIWrQhmyzQDiyZe8Gax1IT+/PI1P+FbNtIQ024G8L0eS+R4DG0GKCSDP5lVXuCfegyw7cOsZjMWmYBNHguYIc91zfuA85xBNoLSlZu5vigB0MrluCa9uKjGrE3fFaTvh93/7MPmRI5IKKbV7oTHmQgFGbLY5iimYLfrxcQ9cPfqXGw7170ndzNR4MsqK1fHmUjtj7dPoXYIIeWHr3mYqChvKsTqxdbei3ubRklcAduFax2iI+IpUVmoS1OCOy5nAVpKkw="
    on_success: always
    on_failure: always