version: "3"

services:
  php:
    build: .
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:8080"
    command: sleep infinity
  mariadb:
    image: mariadb
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: craft