version: '3.9'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 33069:3306
    environment:
      MYSQL_ROOT_PASSWORD: craft
      MYSQL_DATABASE: craft_test
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']
      interval: 10s
      retries: 5
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
  postgres:
    image: postgres:11-alpine
    ports:
      - 54329:5432
    environment:
      POSTGRES_PASSWORD: craft
      POSTGRES_USER: craft
      POSTGRES_DB: craft_test
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'craft', '-d', 'craft_test']
      interval: 5s
      retries: 3
  playwright:
    build:
      context: ../../../
      target: craft
      dockerfile: ./node_modules/@craftcms/playwright/Dockerfile
    ports:
      - ${PLAYWRIGHT_SITE_PORT:-8089}:80
    environment:
      CRAFT_APP_ID: ${PLAYWRIGHT_CRAFT_APP_ID:-CraftCMS}
      CRAFT_ENVIRONMENT: ${PLAYWRIGHT_CRAFT_ENVIRONMENT:-dev}
      CRAFT_SECURITY_KEY: ${PLAYWRIGHT_CRAFT_SECURITY_KEY:-1234567890}
      CRAFT_CP_TRIGGER: ${PLAYWRIGHT_CRAFT_CP_TRIGGER:-admin}
      CRAFT_DB_DRIVER: ${PLAYWRIGHT_CRAFT_DB_DRIVER:-mysql}
      CRAFT_DB_SERVER: ${PLAYWRIGHT_CRAFT_DB_SERVER:-mysql}
      CRAFT_DB_PORT: ${PLAYWRIGHT_CRAFT_DB_PORT:-3306}
      CRAFT_DB_DATABASE: ${PLAYWRIGHT_CRAFT_DB_DATABASE:-craft_test}
      CRAFT_DB_USER: ${PLAYWRIGHT_CRAFT_DB_USER:-craft}
      CRAFT_DB_PASSWORD: ${PLAYWRIGHT_CRAFT_DB_PASSWORD:-craft}
      CRAFT_DB_SCHEMA: ${PLAYWRIGHT_CRAFT_DB_SCHEMA:-}
      CRAFT_DB_TABLE_PREFIX: ${PLAYWRIGHT_CRAFT_DB_TABLE_PREFIX:-}
      PRIMARY_SITE_URL: ${PLAYWRIGHT_SITE_DOMAIN:-http://127.0.0.1/}
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ../../../.:/app/repos/repo/
