name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - '4.0'
      - feature/ghaction2
  pull_request:

jobs:

  call-workflow:
    uses: craftcms/.github/.github/workflows/ci.yml@main
    with:
      run_ecs: true
      run_phpstan: true
      run_tests: true