name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - '4.0'
      - feature/ghaction2
  pull_request:

jobs:

  call-workflow:
    uses: craftcms/.github/.github/workflows/ci.yml@main
    with:
      run_ecs: false
      run_phpstan: true
      run_tests: true
      php_versions: '["7.4", "8.0", "8.1"]'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}