name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - v3
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: craftcms/.github/.github/workflows/ci.yml@v3
    with:
      craft_version: '4'
      jobs: '["ecs", "prettier", "phpstan", "tests]'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_CRAFT_WEBHOOK_URL }}