name: zip-c3
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.?[0-9]?'
jobs:

  build-release:
    name: Build manual zip files
    runs-on: ubuntu-latest

    steps:
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        name: composer install Craft 3
        if: ${{ startsWith(github.ref_name, '3') }}
        with:
          php_version: "7.2"
          dev: no
          php_extensions: pcre zip
          command: create-project craftcms/craft craft-workspace

      - uses: php-actions/composer@v6
        name: composer install Craft 4
        if: ${{ startsWith(github.ref_name, '4') || startsWith(github.ref_name, '99') }}
        with:
          php_version: "8.0"
          dev: no
          php_extensions: pcre zip
          command: create-project craftcms/craft craft-workspace

      - name: Move .env
        run: sudo mv craft-workspace/.env.example craft-workspace/.env

      - name: Create compressed files
        run: |
          cd craft-workspace
          sudo zip -r Craft-${{github.ref_name}}.zip *
          sudo mv Craft-${{github.ref_name}}.zip ../
          sudo tar -zcvf Craft-${{github.ref_name}}.tar.gz *
          sudo mv Craft-${{github.ref_name}}.tar.gz ../

#      - name: Create Zip
#        uses: thedoctor0/zip-release@master
#        with:
#          type: 'zip'
#          filename: 'craft-release.zip'
#          path: 'craft-workspace'
#          directory: '.'

#      - name: Create Tar
#        uses: thedoctor0/zip-release@master
#        with:
#          type: 'tar'
#          filename: 'craft-release.tar.gz'
#          directory: 'craft-workspace'

      - name: Add zip to archive
        uses: actions/upload-artifact@v3
        with:
          name: Craft-${{github.ref_name}}.zip
          path: Craft-${{github.ref_name}}.zip

      - name: Add tar.gz to archive
        uses: actions/upload-artifact@v3
        with:
          name: Craft-${{github.ref_name}}.tar.gz
          path: Craft-${{github.ref_name}}.tar.gz

      - name: Debug
        run: echo ${{github.ref_name}}


#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run script file
#      run: |
#        chmod +x ./public/scripts/test.sh
#        ./public/scripts/test.sh



#      shell: bash
#      - uses: actions/checkout@master
#      - name: Create Zip
#        uses: thedoctor0/zip-release@master
#        with:
#          type: 'zip'
#          filename: 'Craft-release.zip'
#          exclusions: '*.git* /*node_modules/* .editorconfig'
#  notify-slack:
#    name: Notify Slack
#    needs: [ ecs, codecept ]
#    if: ${{ always() }}
#    uses: craftcms/.github/.github/workflows/notify-slack.yml@v1
#    with:
#      success: ${{ needs.ecs.result == 'success' && needs.codecept.result == 'success' }}
#      failure_text_prefix: <!subteam^SGFL9NKNZ>
#    secrets:
#      token: ${{ secrets.GITHUB_TOKEN }}
#      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
